# 스프링부트 공통 설정!
spring:
  application:
    name: mulmi-backend

  profiles:
    default: local

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB

springdoc:
  swagger-ui:
    path: /mulmi-api
  api-docs:
    path: /api-docs

server:
  port: ${SERVER_PORT:8080}

jwt:
  token:
    expiration:
      access: 14400000

app:
  storage:
    s3:
      region: ${AWS_REGION:ap-northeast-2}
      bucket: ${S3_BUCKET:mulmi-dev-files-563586109665}
